### ISSUE TITLE
problems with install

### ISSUE THREAD

**Issue by Vallebueno** [heroalone/Garfield#1]
No instances of Garfield to run after install,

even that it reports that all dependencies are correctly installed , dont manage to call Garfield from the path.

i am running R 4.4 so I had to install logicFS via https://www.bioconductor.org/packages/devel/bioc/html/logicFS.html

still sending error below.

do you have a docker container by any chance?

use cpanm at: /usr/local/bin/cpanm

Usage: cpanm [options] Module [...]

Try `cpanm --help` or `man cpanm` for more options.
sh: 2: --local-lib=~/perl5: not found
Perl module Benchmark is already installed.
Perl module FindBin is already installed.
Perl module File::Spec is already installed.
Perl module Pod::Usage is already installed.
Perl module Getopt::Long::Subcommand is already installed.
Perl module Fcntl is already installed.
Perl module Parallel::ForkManager is already installed.
Rscript found in the PATH.
Installing R libraries
'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.20 (BiocManager 1.30.23), R 4.4.0 (2024-04-24)
Old packages: 'codetools', 'lattice', 'MASS', 'Matrix', 'mgcv', 'nlme',
  'spatial', 'survival'
Warning message:
package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'logicFS'
Required R packages have been successfully installed!

All dependencies have been satisfied.
Now you can take Garfield on your journey!

 ██████╗  █████╗ ██████╗ ███████╗██╗███████╗██╗     ██████╗
██╔════╝ ██╔══██╗██╔══██╗██╔════╝██║██╔════╝██║     ██╔══██╗
██║  ███╗███████║██████╔╝█████╗  ██║█████╗  ██║     ██║  ██║
██║   ██║██╔══██║██╔══██╗██╔══╝  ██║██╔══╝  ██║     ██║  ██║
╚██████╔╝██║  ██║██║  ██║██║     ██║███████╗███████╗██████╔╝
 ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚══════╝╚══════╝╚═════╝

  /\_/\    ~~~ MEOW ~~~
 ( o.o )
  > ^ <

**Comment by heroalone** [comment]
Hey Miguel,
It seems you have installed it successfully and just have no access to run it, since it was not added successfully to the $PATH.

Can you try the absolute path, like:
`sudo ./Garfield`

Or `chmod 755` to change the right of the program/folder?

Please let me know if this works and we can continue to the next solution :)
